spring.application.name=sistema-ventas

# Conexion a la base de datos en Xammp

spring.datasource.url=jdbc:mysql://localhost:3306/db_cafeteria?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=

# aqui el spring crea la putas tablas solito, asi no hago ni madre
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
